/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\model.gltf --transform 
Files: .\model.gltf [5.59KB] > C:\Users\FTMA\Desktop\xanaxProject\XANAXSITE\src\assets\model-transformed.glb [95.17KB] (-1603%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('./model-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.object_0_Baked.geometry} material={materials.object_0_Baked} position={[1.591, 1.569, -2.549]} rotation={[0, 0, -Math.PI / 2]} scale={[0.875, 1, 1]} />
      <mesh geometry={nodes.object_1_Baked.geometry} material={materials.object_1_Baked} position={[1.595, 1.569, -2.54]} rotation={[0, 0, -Math.PI / 2]} scale={[0.875, 1, 1]} />
      <mesh geometry={nodes.object_8_Baked.geometry} material={materials.object_8_Baked} position={[1.676, 1.624, -2.406]} rotation={[0, 0, -Math.PI / 2]} scale={[0.875, 1, 1]} />
    </group>
  )
}

useGLTF.preload('./model-transformed.glb')
